baseurl = "sezgink.github.io"
title = "Sertan Sezgin Kutlu"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "ssezginkutlu"

[params]
  author = "Sertan Sezgin Kutlu"
  info = "Software Engineer, Data Engineer, Backend Developer"
  description = "Sertan Kutlu's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/sertanImage.png"
  #gravatar = "sezginkutlu00@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sezgink/"
  [[params.social]]
  name = "Linked-in"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/sertan-sezgin-kutlu/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"